# Examples Algebra

In [6]:
import numpy as np

EXAMPLE VECTOR (ARRAY)

In [7]:
v=np.array([1,2,3])
u=np.array([4,5,6])

In [8]:
a=np.dot(v,u) #producte escalar
print(a)

32


In [9]:
print(u)

[4 5 6]


In [10]:
b=np.cross(v,u)  #producte vectorialS
print(b)

[-3  6 -3]


EXEMPLES MATRIUS

In [11]:
c=np.array([u,v])
print(c)

[[4 5 6]
 [1 2 3]]


In [12]:
d=c[0] #coge la primera columna
print(d)

[4 5 6]


In [13]:
e=c[0,0] #primero la fila y luego la columna
print(e)

4


In [14]:
f=c[:,1]
print(f)

[5 2]


In [18]:
A=np.array([u,v,u])
print(A)

AttributeError: type object 'float' has no attribute 'np'

VECTORS PROPIS

In [21]:
valors,vectors=np.linalg.eig(A)  #enteindo q el orden es importante
print("valors propis", valors)
print("valors vectors", vectors)

valors propis [ 1.20000000e+01 -1.36526837e-08  1.36526845e-08]
valors vectors [[ 0.68041382  0.40824828 -0.4082483 ]
 [ 0.27216553 -0.81649658  0.81649658]
 [ 0.68041382  0.4082483  -0.40824828]]


In [17]:
#Per comprovar  q efectivament es el valor porpi, basicament fer la multiplicaio

In [ ]:
Pedirle a algn q me pase la libreta o mirar para hacer esta comparacion, tienes q guardar los vectores cmo una variable